name: Sync Image to Aliyun  Example
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Git pull
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1
 
    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: popgenomisc-cn-beijing.cr.volces.com
        username: yirong_yang@1324832
        password: Yyrlyoko123
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://docker.io/nvidia/cuda:12.1.0-cudnn8-devel-ubuntu20.04 docker://popgenomisc-cn-beijing.cr.volces.com/popgenomics/cuda:12.1.0-cudnn8-devel-ubuntu20.04
      # 使用 skopeo 工具将镜像同步到阿里云个人仓库中，使用时请自行源和目标修改仓库名称和镜像名称